name: eskmeans
channels:
  - conda-forge
dependencies:
  - python=3
  - git
  - joblib
  - jupyter
  - nose
  - matplotlib
  - ipython
  - numpy
  - pip
  - librosa
  - scipy
  - tqdm
  - pip:
     - git+https://github.com/detly/gammatone.git
